English = {
    "prefix": "EN",
    "APP_TITLE": "Maroc Covid19",
    "Infected_Tested": "Infected/Tested",
    "Infected": "Infected",
    "Deaths": "Deaths",
    "Recovered": "Recovered",
    "Active Cases": "Active Cases",
    "Map": "Map",
    "Table": "Table",
    "pred_drop_1": "Prediction Using Machine Learning - Gradient Boosting",
    "pred_drop_2": "Calculate Infected Using Deaths History and Mortality Rate",
    "pred_drop_3": "Prediction Using Machine Learning - Neural network (KERAS-based)",
    "Mortality_Rate_input": "Death Ratio (Mortality Rate %) :",
    "Update_message": "Last Update",
    "Soon": "WILL BE ADDED SOON",
    "Current Infected": "Current Infected",
    "Calculated With Ratio": "Calculated With Ratio",
    "Estimation_title": "Estimating Infections  Using Deaths History with Mortality Ratio",
    "Time": "Time",
    "People Counter": "People Counter",
    "Quarantine Started": "Quarantine Started",
    "Prediction": "Prediction",
    "predicition_graph_title": "Predictions of infected People next 10 Days ( Till",
    "Tests_per_country": "Tests Counter",
    "Countries": "Countries",
    "Date": "Date",
    "Testing_title": "Testing for COVID-19",
    "Time_line_title": "Time Line of Infections, Deaths and Recovered",
    "Choose_map": "Choose a Display Map",
    "note": "**Note :** There is **No** political intention behind the used maps ,I choosed _stamen-watercolor_  Because it doesn have borders :)",
    "Infections_per_regions_table": "Infections per regions table",
    "week": "Week",
    "month": "Month",
    "All": "All",
}
Arabic = {
    "prefix": "AR",
    "APP_TITLE": "Maroc Covid19",
    "Infected_Tested": "اختبار/ مصاب",
    "Deaths": "الوفيات",
    "Recovered": "شفاء",
    "Infected": "مصاب",
    "Active Cases": "الحالات النشطة",
    "Map": "خريطة",
    "Table": "جدول البيانات",
    "pred_drop_1": "التنبؤ باستخدام التعلم الآلي - Gradient Boosting",
    "pred_drop_2": "حساب المصابين باستخدام تاريخ الوفيات ومعدل الوفيات المعروف",
    "pred_drop_3": "التنبؤ باستخدام التعلم الآلي - Neural network (KERAS-based)",
    "Mortality_Rate_input": "معدل الوفيات (معدل الوفيات ٪)",
    "Update_message": "اخر تحديث",
    "Soon": "ستضاف قريبا",
    "Current Infected": "مصاب حاليا",
    "Calculated With Ratio": "محسوب بواسطة النسبة",
    "Estimation_title": "تقدير المصابين باستخدام تاريخ الوفيات مع معدل الوفيات",
    "Time": "تاريخ",
    "People Counter": "عداد الناس",
    "Quarantine Started": "بداية الحجر الصحي",
    "Prediction": "التوقعات",
    "predicition_graph_title": "توقعات المصابين بعد 10 أيام (حتى",
    "Tests_per_country": "عداد الاختبارات",
    "Countries": "بلدان",
    "Date": "تاريخ",
    "Testing_title": "اختبارات COVID-19",
    "Time_line_title": "الخط الزمني للعدوى ,الوفيات والشفاء",
    "Choose_map": "اختيار خريطة",
    "note": "** ملاحظة: ** لا توجد نية سياسية وراء الخرائط المستخدمة :)",
    "Infections_per_regions_table": "جدول العدوى في المناطق",
    "week": "Week",
    "month": "Month",
    "All": "All",
}
